LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_SRC_FILES := mmap.c

LOCAL_MODULE_CFLAGS += -Wall -Wextra -g -O0 -ggdb
LOCAL_MODULE := mmap
LOCAL_MULTILIB := both
LOCAL_MODULE_STEM_32 := $(LOCAL_MODULE)32
LOCAL_MODULE_STEM_64 := $(LOCAL_MODULE)64

include $(BUILD_EXECUTABLE)

###

include $(CLEAR_VARS)

LOCAL_SRC_FILES := vmalloc.c

LOCAL_MODULE_CFLAGS += -Wall -Wextra -g -O0 -ggdb
LOCAL_MODULE := vmalloc
LOCAL_MULTILIB := both
LOCAL_MODULE_STEM_32 := $(LOCAL_MODULE)32
LOCAL_MODULE_STEM_64 := $(LOCAL_MODULE)64

include $(BUILD_EXECUTABLE)

###

include $(CLEAR_VARS)

LOCAL_SRC_FILES := fstat.c

LOCAL_MODULE_CFLAGS += -Wall -Wextra -g -O0 -ggdb
LOCAL_MODULE := fstat
LOCAL_MULTILIB := both
LOCAL_MODULE_STEM_32 := $(LOCAL_MODULE)32
LOCAL_MODULE_STEM_64 := $(LOCAL_MODULE)64

include $(BUILD_EXECUTABLE)

###

include $(CLEAR_VARS)

LOCAL_SRC_FILES := fread.c

LOCAL_MODULE_CFLAGS += -Wall -Wextra -g -O0 -ggdb
LOCAL_MODULE := fread
LOCAL_MULTILIB := both
LOCAL_MODULE_STEM_32 := $(LOCAL_MODULE)32
LOCAL_MODULE_STEM_64 := $(LOCAL_MODULE)64

include $(BUILD_EXECUTABLE)

###

include $(CLEAR_VARS)

LOCAL_SRC_FILES := fread.c

LOCAL_MODULE_CFLAGS += -Wall -Wextra -g -O0 -ggdb
LOCAL_MODULE := fread_static
LOCAL_MULTILIB := both
LOCAL_MODULE_STEM_32 := $(LOCAL_MODULE)32
LOCAL_MODULE_STEM_64 := $(LOCAL_MODULE)64

LOCAL_STATIC_LIBRARIES := libc libm
LOCAL_FORCE_STATIC_EXECUTABLE := true

include $(BUILD_EXECUTABLE)

###

include $(CLEAR_VARS)

LOCAL_SRC_FILES := mfile.c

LOCAL_MODULE_CFLAGS += -Wall -Wextra -g -O0 -ggdb
LOCAL_MODULE := mfile
LOCAL_MULTILIB := both
LOCAL_MODULE_STEM_32 := $(LOCAL_MODULE)32
LOCAL_MODULE_STEM_64 := $(LOCAL_MODULE)64

include $(BUILD_EXECUTABLE)

###

include $(CLEAR_VARS)

LOCAL_SRC_FILES := malloc.c

LOCAL_MODULE_CFLAGS += -Wall -Wextra -g -O0 -ggdb
LOCAL_MODULE := malloc
LOCAL_MULTILIB := both
LOCAL_MODULE_STEM_32 := $(LOCAL_MODULE)32
LOCAL_MODULE_STEM_64 := $(LOCAL_MODULE)64

include $(BUILD_EXECUTABLE)

###

include $(CLEAR_VARS)

LOCAL_SRC_FILES := rw.c

LOCAL_MODULE_CFLAGS += -Wall -Wextra -g -O0 -ggdb
LOCAL_MODULE := rw
LOCAL_MULTILIB := both
LOCAL_MODULE_STEM_32 := $(LOCAL_MODULE)32
LOCAL_MODULE_STEM_64 := $(LOCAL_MODULE)64

include $(BUILD_EXECUTABLE)

###

include $(CLEAR_VARS)

LOCAL_SRC_FILES := brk.c

LOCAL_MODULE_CFLAGS += -Wall -Wextra -g -O0 -ggdb
LOCAL_MODULE := brk
LOCAL_MULTILIB := both
LOCAL_MODULE_STEM_32 := $(LOCAL_MODULE)32
LOCAL_MODULE_STEM_64 := $(LOCAL_MODULE)64

include $(BUILD_EXECUTABLE)

###

include $(CLEAR_VARS)

LOCAL_SRC_FILES := inputs.c

LOCAL_MODULE_CFLAGS += -Wall -Wextra -g -O0 -ggdb
LOCAL_MODULE := inputs
LOCAL_MULTILIB := both
LOCAL_MODULE_STEM_32 := $(LOCAL_MODULE)32
LOCAL_MODULE_STEM_64 := $(LOCAL_MODULE)64

include $(BUILD_EXECUTABLE)

