# extra bashrc: executed by ~/.bashrc
# ln -s ./bash_aliases ~/.bash_aliases

export PATH=~/Android/Sdk/platform-tools:$PATH

# Build Android
export USE_CCACHE=1
export CCACHE_DIR=~/.ccache

# byobu-prompt
# [ -r ~/.byobu/prompt ] && . ~/.byobu/prompt

export SMTP_USER=`cat ~/.ssh/smtp_user`
export SMTP_PASS=`cat ~/.ssh/smtp_pass`

export VISUAL=vim
export EDITOR=vim

export GOPATH=~/vobs/gocode
export AWS_REGION=us-west-2

# KVM/QEMU uses system instead of user session
export LIBVIRT_DEFAULT_URI='qemu:///system'

#export LANG=C

alias aa='. choose_adb.sh'
alias reboot='reboot.sh'
alias mk='rm -f $OUT/ramdisk.img && m -j 16 bootimage'
alias cerbero='~/vobs/cerbero/cerbero-uninstalled'

repo ()
{
    if [[ "$1" = "sync" ]]; then
        if [[ "$*" != *" -c"* ]]; then
            echo "Sync without -c; aborting.";
            return 1;
        fi;
    fi;
    command repo "$@"
}

export PROXY_IP=10.123.206.155
export PROXY_PORT=3128

proxy_on() {
	export proxy=http://${PROXY_IP}:${PROXY_PORT}
	export http_proxy=http://${PROXY_IP}:${PROXY_PORT}
	export https_proxy=http://${PROXY_IP}:${PROXY_PORT}
	export no_proxy='localhost,127.0.0.*,10.*,100.*,*.huawei.com'
	echo -e "Proxy ON"
}

proxy_off() {
	unset http_proxy https_proxy
	echo -e "Proxy OFF"
}

export NODE_TLS_REJECT_UNAUTHORIZED=0

