[Interface]
#Alias = wlwg0blue
Address = 10.11.0.3/24
ListenPort = 51820
PrivateKey = QG5Zd/jq9sKqUoDspirwEquqD/SHzzKjPAANKDVbTm8=
DNS = 10.11.0.1

[Peer]
#Alias = Router
PublicKey = ynkSnGK3mHvV4ASRyqgMNvo95Gx8NdBpNy8NfNjHJX8=
PresharedKey = m7YxfT5daOUXaHSUAE5OjmXIGqGFYL/h5BPFSVxQbZM=
AllowedIPs = 0.0.0.0/0
Endpoint = wl.freemyip.com:51820
PersistentKeepalive = 25
